{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T07:53:15.311Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T07:54:15.557Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:33:35.041Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:36:38.835Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:39:37.050Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:40:17.154Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:41:45.321Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:46:06.817Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:47:03.231Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:47:46.440Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:48:16.297Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:48:50.740Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:52:07.344Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:53:17.148Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:53:46.360Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:54:50.623Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:56:40.474Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T10:59:19.213Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Error: Invalid Chai property: statusCode","service":"user-service","stack":"Error: Error: Invalid Chai property: statusCode\n    at Context.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\tests\\feature.test.js:26:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-01-28T10:59:19.477Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:00:09.153Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:04:25.701Z"}
{"level":"\u001b[31merror\u001b[39m","message":"ReferenceError: expect is not defined","service":"user-service","stack":"Error: ReferenceError: expect is not defined\n    at Context.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\tests\\feature.test.js:26:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-01-28T11:04:25.961Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:12:23.021Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:15:33.852Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:16:02.875Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:16:18.751Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:16:49.001Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:18:20.821Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:18:43.327Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:18:58.222Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:19:20.703Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:19:39.499Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:20:14.211Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:21:59.434Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:25:33.631Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:26:09.468Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:31:04.071Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:32:15.991Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:33:34.633Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:35:02.894Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:35:40.221Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:36:05.975Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:37:55.341Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:39:48.636Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:40:59.227Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:41:28.869Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:46:23.019Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:50:09.063Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:50:33.919Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:54:52.904Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:55:15.641Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:56:43.225Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:57:19.137Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T11:58:05.865Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T12:00:00.539Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T12:01:07.370Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T12:02:51.942Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T12:04:07.459Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T12:06:53.370Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T12:07:24.689Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T12:09:08.275Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T12:11:26.460Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T12:15:25.075Z"}
{"level":"\u001b[31merror\u001b[39m","message":"here goes a fake error","service":"user-service","stack":"Error: here goes a fake error\n    at Server.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\server.js:14:16)\n    at Object.onceWrapper (node:events:509:28)\n    at Server.emit (node:events:390:28)\n    at emitListeningNT (node:net:1368:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2022-01-28T12:16:20.992Z"}
{"level":"\u001b[31merror\u001b[39m","message":"Error: Include unexpected. Element has to be either a Model, an Association or an object.","service":"user-service","stack":"Error: Error: Include unexpected. Element has to be either a Model, an Association or an object.\n    at VehicleService.getVehicleEstimatedArrival (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:160:20)\n    at async Context.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\tests\\unit.test.js:42:24)","timestamp":"2022-01-29T19:09:06.538Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleAverageTravelTime (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:98:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async getVehicleAverageTravelTime (C:\\Users\\verky\\projects\\shuttlers\\test_api\\controllers\\vehicles.controller.js:7:18)","timestamp":"2022-02-03T22:42:18.599Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleEstimatedArrival (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:160:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async getVehicleEstimatedArrival (C:\\Users\\verky\\projects\\shuttlers\\test_api\\controllers\\vehicles.controller.js:17:18)","timestamp":"2022-02-03T22:42:18.663Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleTelemetries (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:50:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Context.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\tests\\unit.test.js:11:23)","timestamp":"2022-02-03T22:42:18.670Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleTelemetries (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:50:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Context.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\tests\\unit.test.js:17:23)","timestamp":"2022-02-03T22:42:18.697Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleTelemetries (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:50:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Context.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\tests\\unit.test.js:23:22)","timestamp":"2022-02-03T22:42:18.700Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleEstimatedArrival (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:160:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Context.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\tests\\unit.test.js:41:24)","timestamp":"2022-02-03T22:42:18.705Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleAverageTravelTime (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:98:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async getVehicleAverageTravelTime (C:\\Users\\verky\\projects\\shuttlers\\test_api\\controllers\\vehicles.controller.js:7:18)","timestamp":"2022-02-03T22:45:19.168Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleEstimatedArrival (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:160:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async getVehicleEstimatedArrival (C:\\Users\\verky\\projects\\shuttlers\\test_api\\controllers\\vehicles.controller.js:17:18)","timestamp":"2022-02-03T22:45:19.190Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleTelemetries (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:50:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Context.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\tests\\unit.test.js:11:23)","timestamp":"2022-02-03T22:45:19.196Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleTelemetries (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:50:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Context.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\tests\\unit.test.js:17:23)","timestamp":"2022-02-03T22:45:19.201Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleTelemetries (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:50:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Context.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\tests\\unit.test.js:23:22)","timestamp":"2022-02-03T22:45:19.205Z"}
{"level":"\u001b[31merror\u001b[39m","message":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306","service":"user-service","stack":"Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at VehicleService.getVehicleEstimatedArrival (C:\\Users\\verky\\projects\\shuttlers\\test_api\\services\\vehicleTelemetry.service.js:160:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Context.<anonymous> (C:\\Users\\verky\\projects\\shuttlers\\test_api\\tests\\unit.test.js:41:24)","timestamp":"2022-02-03T22:45:19.209Z"}
